# Generated by Django 3.0.4 on 2020-03-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('time', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('creation_date', models.DateField(default=datetime.datetime(2020, 3, 9, 16, 41, 36, 653328))),
            ],
        ),
    ]
