# Generated by Django 3.0.4 on 2020-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0003_receita_owner_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
