# Generated by Django 3.0.4 on 2020-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0004_receita_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%d/%m/%Y'),
        ),
    ]
