# Generated by Django 3.0.4 on 2020-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoasapp', '0001_initial'),
        ('receitasapp', '0002_auto_20200310_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='owner_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoasapp.Pessoa'),
            preserve_default=False,
        ),
    ]
